config/routes.rb
Rails.application.routes.draw do
  resources :visitors
  resources :invitations
  get "/users" => "users#create"
  resources :users do
    member do 
    get 'invitations'
  end
  collection do
    get 'login'
  end
  end
  devise_for :company_users
  resources :company_users do
    collection do
    get 'new_invite'
    get 'search_user'
    post 'invite'
    get 'scan'
    get 'scan'
  end
  end
  resources :tenants

  root 'tenants#index'

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :user
  before_save :gen_qrcode
  def gen_qrcode
    code =  Time.now.to_i.to_s
    RQRCode::QRCode.new( code,
     :size => 4,
     :level => :h ).to_img_rgba([0,0,0,0],[0,0,0,255]).resize(500,500).save("public/qr_codes/invitations/" + code + ".png")
    self.qr_code_url = "https://helloapph.herokuapp.com/qr_codes/invitations/" + code + ".png"
    self.code = code
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_invitation, only: [:show, :edit, :update, :destroy]

  # GET /invitations
  # GET /invitations.json
  def index
    @invitations = Invitation.all
  end

  # GET /invitations/1
  # GET /invitations/1.json
  def show
  end

  # GET /invitations/new
  def new
    @invitation = Invitation.new
  end

  # GET /invitations/1/edit
  def edit
  end

  # POST /invitations
  # POST /invitations.json
  def create
    @invitation = Invitation.new(invitation_params)

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to @invitation, notice: 'Invitation was successfully created.' }
        format.json { render :show, status: :created, location: @invitation }
      else
        format.html { render :new }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invitations/1
  # PATCH/PUT /invitations/1.json
  def update
    respond_to do |format|
      if @invitation.update(invitation_params)
        format.html { redirect_to @invitation, notice: 'Invitation was successfully updated.' }
        format.json { render :show, status: :ok, location: @invitation }
      else
        format.html { render :edit }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1
  # DELETE /invitations/1.json
  def destroy
    @invitation.destroy
    respond_to do |format|
      format.html { redirect_to invitations_url, notice: 'Invitation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invitation
      @invitation = Invitation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invitation_params
      params.require(:invitation).permit(:email, :user_id, :invitation_date, :purpose, :qr_code_url)
    end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_for(@invitation) do |f| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
      <% @invitation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :invitation_date %><br>
    <%= f.datetime_select :invitation_date %>
  </div>
  <div class="field">
    <%= f.label :purpose %><br>
    <%= f.text_field :purpose %>
  </div>
  <div class="field">
    <%= f.label :qr_code_url %><br>
    <%= f.text_field :qr_code_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing Invitation</h1>

<%= render 'form' %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Invitations</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>User</th>
      <th>Invitation date</th>
      <th>Purpose</th>
      <th>Qr code url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invitations.each do |invitation| %>
      <tr>
        <td><%= invitation.email %></td>
        <td><%= invitation.user %></td>
        <td><%= invitation.invitation_date %></td>
        <td><%= invitation.purpose %></td>
        <td><%= invitation.qr_code_url %></td>
        <td><%= link_to 'Show', invitation %></td>
        <td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
        <td><%= link_to 'Destroy', invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invitation', new_invitation_path %>

app/views/invitations/new.html.erb
<h1>New Invitation</h1>

<%= render 'form' %>

<%= link_to 'Back', invitations_path %>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @invitation.email %>
</p>

<p>
  <strong>User:</strong>
  <%= @invitation.user %>
</p>

<p>
  <strong>Invitation date:</strong>
  <%= @invitation.invitation_date %>
</p>

<p>
  <strong>Purpose:</strong>
  <%= @invitation.purpose %>
</p>

<p>
  <strong>Qr code url:</strong>
  <%= @invitation.qr_code_url %>
</p>

<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>