config/routes.rb
Rails.application.routes.draw do
  resources :visitors
  resources :invitations
  get "/users" => "users#create"
  resources :users do
    member do 
    get 'invitations'
  end
  collection do
    get 'login'
  end
  end
  devise_for :company_users
  resources :company_users do
    collection do
    get 'new_invite'
    get 'search_user'
    post 'invite'
    get 'scan'
    get 'scan'
  end
  end
  resources :tenants

  root 'tenants#index'

end

app/models/company_user.rb
class CompanyUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/company_users_controller.rb
class CompanyUsersController < ApplicationController
  before_action :set_company_user, only: [:show, :edit, :update, :destroy]

  # GET /company_users
  # GET /company_users.json
  def index
    @company_users = CompanyUser.all
  end

  # GET /company_users/1
  # GET /company_users/1.json
  def show
  end

  # GET /company_users/new
  def new
    @company_user = CompanyUser.new
  end

  # GET /company_users/1/edit
  def edit
  end

  # POST /company_users
  # POST /company_users.json
  def create
    @company_user = CompanyUser.new(company_user_params)

    respond_to do |format|
      if @company_user.save
        format.html { redirect_to @company_user, notice: 'Company user was successfully created.' }
        format.json { render :show, status: :created, location: @company_user }
      else
        format.html { render :new }
        format.json { render json: @company_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company_users/1
  # PATCH/PUT /company_users/1.json
  def update
    respond_to do |format|
      if @company_user.update(company_user_params)
        format.html { redirect_to @company_user, notice: 'Company user was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_user }
      else
        format.html { render :edit }
        format.json { render json: @company_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company_users/1
  # DELETE /company_users/1.json
  def destroy
    @company_user.destroy
    respond_to do |format|
      format.html { redirect_to company_users_url, notice: 'Company user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def search_user
    user = User.find_by(email: params[:email])
    if user
      data = {user: user, message: "User found"}
    else
      data = {user: nil, message: "User not found"}
    end
    render json: data
  end
  def invite

    user = User.find(params[:value].to_i) if params[:type] == "id"
    invitation  = Invitation.new
    if user
      invitation.email = user.email
      invitation.user_id = user.id 
      invitation.poc = params[:poc]
      invitation.purpose = params[:purpose]  
    else
      invitation.email = params[:value]
    end
    invitation.save
    render json: {}
  end

  def scan
    invitation = Invitation.where(code: params[:code], active: nil).first
    if invitation 
      invitation.active = false
      invitation.save
      user = invitation.user
      Visitor.create(name: user.name, email: user.email, purpose: invitation.purpose, poc: invitation.poc)
      status_text = "success"
    else
      status_text=  "failure"
    end
    render json: {status: 200, status_text: status_text}
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_user
      @company_user = CompanyUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_user_params
      params.require(:company_user).permit(:name, :email, :phone_number)
    end
end

app/helpers/company_users_helper.rb
module CompanyUsersHelper
end

app/views/company_users/_form.html.erb
<%= form_for(@company_user) do |f| %>
  <% if @company_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company_user.errors.count, "error") %> prohibited this company_user from being saved:</h2>

      <ul>
      <% @company_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/company_users/edit.html.erb
<h1>Editing Company User</h1>

<%= render 'form' %>

<%= link_to 'Show', @company_user %> |
<%= link_to 'Back', company_users_path %>

app/views/company_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Company Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @company_users.each do |company_user| %>
      <tr>
        <td><%= company_user.name %></td>
        <td><%= company_user.email %></td>
        <td><%= company_user.phone_number %></td>
        <td><%= link_to 'Show', company_user %></td>
        <td><%= link_to 'Edit', edit_company_user_path(company_user) %></td>
        <td><%= link_to 'Destroy', company_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company user', new_company_user_path %>

app/views/company_users/new.html.erb
<h1>New Company User</h1>

<%= render 'form' %>

<%= link_to 'Back', company_users_path %>

app/views/company_users/new_invite.html.erb
<input type="text" class="user_email" />
<a href="#" onClick="CompanyUser.searchUser()">Search</a>

<div id="user_info_container"></div>

<script type="text/template" id="user_info">
{{#if user}}
<div class="user">
  <h1>{{user.name}}</h1>
  <div >
    {{{user.email}}} <br/>
     {{{user.phone_number}}}
  </div>
<a href="#" class="invite" onClick="CompanyUser.inviteUser('id', '{{user.id}}')">
  Invite</a>
</div>
{{else}}
User not found
* An email will be sent to the user with QRcode<br/>
  <a href="#" class="invite" onClick="CompanyUser.inviteUser('email', '{{email}}')">Anyway Invite </a>
{{/if}}
</script>

app/views/company_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company_user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @company_user.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @company_user.phone_number %>
</p>

<%= link_to 'Edit', edit_company_user_path(@company_user) %> |
<%= link_to 'Back', company_users_path %>